# Generated by Django 4.0.6 on 2022-08-15 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasTarjeta',
            fields=[
                ('marca_id', models.IntegerField(primary_key=True, serialize=False)),
                ('marca_name', models.TextField()),
            ],
            options={
                'db_table': 'marcas_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('numero', models.TextField(max_length=16, primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('cvv', models.IntegerField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('fecha_emision', models.TextField()),
                ('fecha_vto', models.TextField()),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
    ]
