# Generated by Django 4.0.6 on 2022-08-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCuenta',
            fields=[
                ('tipo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_name', models.TextField()),
            ],
            options={
                'db_table': 'tipos_cuenta',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': False},
        ),
    ]
