# Generated by Django 4.0.6 on 2022-08-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direcciones',
            options={'managed': False},
        ),
    ]
